I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sandbox/events_loader.rpy", line 1, in script
    init python:
  File "game/sandbox/events_loader.rpy", line 7, in <module>
    script_dir = os.path.dirname(os.path.abspath(__file__))
NameError: name '__file__' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sandbox/events_loader.rpy", line 1, in script
    init python:
  File "C:\Users\User\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\User\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/sandbox/events_loader.rpy", line 7, in <module>
    script_dir = os.path.dirname(os.path.abspath(__file__))
NameError: name '__file__' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
EventTester 1.0
Thu Sep  4 01:13:10 2025
